### ISSUE TITLE
Update your code

### ISSUE THREAD

**Issue by Stepandanci** [IuraT/SaltEdge_Interview#1]
Read again test task and update your code.

Make your changes in `dev` branch. 
Open a new pull request from branch `dev` to `master` for review.

1. Read Ruby style guide.
You can install `rubocop` gem for refactor code.

2. Save result of your script (accounts and transactions) in a JSON file.
I need to check parsed data.

3. Rename Customer class to Account.
Customer is owner of accounts.

4. Use Nokogiri gem.
In this test task required to use Nokogiri gem.
Nokogiri reduces the number of browser requests.
You fetch HTML data from browser and parse it a method.

5. Update fetch logic.
Separate methods for `fetch` and `parse` data.

#### Example code structure:

```ruby
class ExampleBank

  def execute
    connect
    fetch_accounts
    fetch_transactions
    save_result # save in JSON file
  end

  def connect
    # here you log in to the bank
  end

  def fetch_accounts
    # fetch html data using Nokogiri, take only fragment of HTML.
    html = Nokogiri::HTML.fragment(browser.div(class: "example").html)
    parse_accounts(html)
  end

  def fetch_transactions
    # go to transactions, save html
    parse_transactions(account, html)
  end

  def parse_accounts(html)
    # parse accounts here
  end

  def parse_transactions(account, html)
    # parse transactions here
  end
end
```

## Write tests

You should write a test that checks the data from demo bank.

1. Read about Rspec. It is a framework for test your code.

- https://rspec.info
- https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers

2. Create `spec.rb` file.

3. Write specs for `parse_accounts` and `parse_transactions`.

4. Take HTML from demo bank and save it in a file (check screenshot).
`html_example = Nokogiri::HTML(File.read('accounts.html'))`

![Снимок](https://user-images.githubusercontent.com/29861352/84526427-f2d8bc80-ace5-11ea-81e2-b36cf686705d.PNG)

5. Call method for parse accounts and send HTML data. `parse_accounts(html_example)`

6. Check the number of accounts and show an example account in a hash format.

Example:
```ruby
it 'check number of accounts and show an example account' do
  html_example = Nokogiri::HTML(File.read('accounts.html'))
  accounts = parse_accounts(html_example) # NOTE: It is my example, not a real code.

  expect(accounts.count).to eq(5)
  expect(accounts.first.to_hash).to eq(
    {
      "name"         => "Demo Everyday Account",
      "currency"     => "USD",
      "balance"      => 1959.90,
      "nature"       => "account",
      "transactions" => []
    }
  )
end
```

7. Do the same for transactions.

Good luck!

**Comment by Stepandanci** [comment]
##   Update format of JSON file
- use `JSON.pretty_generate(data)`
- unite accounts and transactions in one file.
- account balance and transaction amount must be float
- date must be in JSON format "YYYY-MM-DD"
- description can not be blank
- check example from your test task.

```json
{
  "accounts": [
    {
      "name": "account1",
      "currency": "MDL",
      "balance": 300.22,
      "nature": "account",
      "transactions": [
        {
            "date": "2015-01-15",
            "description": "bought food",
            "amount": -20.31,
            "currency": "MDL",
            "account_name": "account1"
        }
      ]
    }
  ]
}
```

**Comment by IuraT** [comment]
I updated the code for the following requirements, unfortunately, I already merged the changes into master.

**Comment by Stepandanci** [comment]
Your code looks better.

1. Move code from `click_actions.rb` to `bendingo_bank.rb`.

2. Each class should be in a separate file.
- Move class `Account` to `account.rb` file
- Move class `Transaction` to `transactions.rb` file

3. Save a JSON file with all parsed data (all accounts with transactions).

4. Show account in hash format. 
In `spec.rb` you have a wrong example.
`expect(accounts[0]).to eq('Demo Everyday Account')`

Please, check my example and update it.
```
expect(accounts.first.to_hash).to eq(
  {
    "name"         => "Demo Everyday Account",
    "currency"     => "USD",
    "balance"      => 1959.90,
    "nature"       => "account",
    "transactions" => []
  }
)
```

4. In `def initialize` delete `@username` and `@password`. 
It is demobank you do not use it.

5. Do not use hard-coded data in code.
`html = Nokogiri::HTML.parse(@browser.div(class: '_23LTBXgogQ').html)`
'_23LTBXgogQ' is random generated class, it will be changed at the next refresh, use `css:` here.

6. Make your changes in `dev` branch.
Open a new pull request from branch `dev` to `master` for review.

**Comment by IuraT** [comment]
I created a pull request with the following changes

**Comment by Stepandanci** [comment]
You will be invited for a second interview.
There are some details that you can update here, but I think your code is good enough.
